language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  app: lychee-pudding-51897 # replace this with the name of your heroku app
  on:
    repo: AlnurFaisal/Match-Pair-of-Numbers   # replace this with your_github_username/your_repo